### ISSUE TITLE
for URIModifier, localhost force breaks my tests

### ISSUE THREAD

**Issue by scottmatth** [aerogear/aerogear-testing-tools#2]
I was very excited to use this feature since it would be a way for us to test our Rest Services over https.  The problem I encountered was that the force of the URL to localhost from 127.0.0.1 makes my tests (which worked before) not work anymore.  I am hesitant to just modify the settings in my JBOSS configuration because these test cases will also be run in our continuous build environment against an instance of our application on a linux server.

Can you explain why it was felt that the URL had to be forced to localhost if it was previously attempting 127.0.0.1?

**Comment by smiklosovic** [comment]
that extension was moved here 

https://github.com/arquillian/arquillian-showcase/tree/master/extensions/arquillian-smart-url

**Comment by matzew** [comment]
@kpiwko @smiklosovic what's the status here ? can we close this one ?

**Comment by smiklosovic** [comment]
@matzew thanks for the remainder, @scottmatth i did super simple solution here (1), far from being perfect but I think it resolves your issue. In case it works to your satisfaction and it is still relevant, let me know and we can cut new version of it just for you.

(1) https://github.com/arquillian/arquillian-showcase/tree/smart-url-localhost/extensions/arquillian-smart-url

**Comment by camilamacedo86** [comment]
I am closing it since it was answered more than 3 years ago.
