### ISSUE TITLE
Unable to set shouldExitWith for JBossCLI

### ISSUE THREAD

**Issue by kpiwko** [aerogear/aerogear-testing-tools#7]
@smiklosovic it looks that JBossCLI is wrapping CommandTool in such way it is not possible to setup 
allowed exit values. Can you please fix that?

// cc @AdamSaleh 

https://github.com/aerogear/aerogear-testing-tools/blob/master/spacelift-jboss-manager/src/main/java/org/jboss/aerogear/test/container/spacelift/JBossCLI.java#L142

**Comment by smiklosovic** [comment]
https://github.com/aerogear/aerogear-testing-tools/commit/3806e8cbc42fa574624fc2339b0f6746876f9656
